export enum ErrorCode {
    USER_UNDEFINED = 'USER_UNDEFINED',
    USER_NOT_FOUND = 'USER_NOT_FOUND',
    USER_TYPE_INVALID = 'USER_TYPE_INVALID',
    USER_STATUS_INVALID = 'USER_STATUS_INVALID',
    USER_LEDGER_NOT_FOUND = 'USER_LEDGER_NOT_FOUND',

    LOGIN_ID_INVALID = 'LOGIN_ID_INVALID',
    LOGIN_TOKEN_INVALID = 'LOGIN_TOKEN_INVALID',
    LOGIN_TOKEN_EXPIRED = 'LOGIN_TOKEN_EXPIRED',
    LOGIN_SIGNATURE_INVALID = 'LOGIN_SIGNATURE_INVALID',

    COIN_UNDEFINED = 'COIN_UNDEFINED',
    COIN_NOT_FOUND = 'COIN_NOT_FOUND',
    COIN_BALANCE_NOT_FOUND = 'COIN_BALANCE_NOT_FOUND',
    COIN_BALANCE_INSUFFICIENT = 'COIN_BALANCE_INSUFFICIENT',

    INVALID_REQUEST = 'INVALID_REQUEST',
}
