export enum ErrorCode {
    USER_UNDEFINED = 'USER_UNDEFINED',
    USER_NOT_FOUND = 'USER_NOT_FOUND',
    USER_TYPE_INVALID = 'USER_TYPE_INVALID',
    USER_STATUS_INVALID = 'USER_STATUS_INVALID',
    USER_LEDGER_NOT_FOUND = 'USER_LEDGER_NOT_FOUND',

    LOGIN_ID_INVALID = 'LOGIN_ID_INVALID',
    LOGIN_TOKEN_INVALID = 'LOGIN_TOKEN_INVALID',
    LOGIN_TOKEN_EXPIRED = 'LOGIN_TOKEN_EXPIRED',
    LOGIN_SIGNATURE_INVALID = 'LOGIN_SIGNATURE_INVALID',
    
    COMPANY_UNDEFINED = 'COMPANY_UNDEFINED',
    COMPANY_NOT_FOUND = 'COMPANY_NOT_FOUND',
    COMPANY_STATUS_INVALID = 'COMPANY_STATUS_INVALID',
    COMPANY_NOT_UNDEFINED = 'COMPANY_NOT_UNDEFINED',
    COMPANY_ROLE_UNDEFINED = 'COMPANY_ROLE_UNDEFINED',
    COMPANY_ROLE_INVALID = 'COMPANY_ROLE_INVALID',
    COMPANY_LEDGER_NOT_FOUND = 'COMPANY_LEDGER_NOT_FOUND',

    COIN_UNDEFINED = 'COIN_UNDEFINED',
    COIN_NOT_FOUND = 'COIN_NOT_FOUND',
    COIN_BALANCE_NOT_FOUND = 'COIN_BALANCE_NOT_FOUND',

    PROJECT_UNDEFINED = 'PROJECT_UNDEFINED',
    PROJECT_NOT_FOUND = 'PROJECT_NOT_FOUND',
    PROJECT_STATUS_INVALID = 'PROJECT_STATUS_INVALID',
    PROJECT_ROLE_UNDEFINED = 'PROJECT_ROLE_UNDEFINED',
    PROJECT_ROLE_INVALID = 'PROJECT_ROLE_INVALID',
    PROJECT_LEDGER_NOT_FOUND = 'PROJECT_LEDGER_NOT_FOUND',

    VOTING_UNDEFINED = 'VOTING_UNDEFINED',
    VOTING_NOT_FOUND = 'VOTING_NOT_FOUND',
    VOTING_STATUS_INVALID = 'VOTING_STATUS_INVALID',
    VOTING_ROLE_UNDEFINED = 'VOTING_ROLE_UNDEFINED',
    VOTING_ROLE_INVALID = 'VOTING_ROLE_INVALID',
    VOTING_LEDGER_NOT_FOUND = 'VOTING_LEDGER_NOT_FOUND',

    INVALID_REQUEST = 'INVALID_REQUEST',
}
