export enum LedgerCompanyRole {
    EXPERT = 'EXPERT',
    PROTECTOR = 'PROTECTOR',

    USER_MANAGER = 'COMPANY_USER_MANAGER',
    COIN_MANAGER = 'COMPANY_COIN_MANAGER',
    COMPANY_MANAGER = 'COMPANY_COMPANY_MANAGER',
    PROJECT_MANAGER = 'COMPANY_PROJECT_MANAGER',
}
